### ISSUE TITLE
Issue with opening/saving tilesets

### ISSUE THREAD

**Issue by YoYoBoBo** [NSMBW-Community/Puzzle-Updated#3] opened 2019-07-22 13:05 UTC
When using PySide2, the program crashes upon trying to open a tileset (even if I just save a blank tileset and try to reopen it). When using PyQt5, the program works for the most part except when saving certain tilesets such as Pa0_jyotyu.arc from New SMBW or Newer SMBW. In these cases the tileset is saved improperly and cannot be opened by any tileset editor (puzzle .6, wart 2.8 etc). The error I get in cmd is:

Traceback (most recent call last):
  File "puzzle.py", line 733, in paint
    curTile = Tileset.tiles[index.row()]
IndexError: list index out of range

When opening with wart I get an error that object collision data is missing.

I'm very new to python so I don't have a clue whats going on. I'm using python 3.7.3. I have tested with versions of PySide2 and PyQt5 from before the last commit and with the latest versions of the two, both having the same problems. I also have tried without and with the updated NSMBlib. Here are the tilesets I tried that have problems.
[tilesets.zip](https://github.com/RoadrunnerWMC/Puzzle-Updated/files/3417504/tilesets.zip)

It did work on other tilesets like cloudscape from newer.

**Comment by YoYoBoBo** [comment] 2019-07-22 13:08
Pa0_WSELTS does save correctly.

**Comment by RoadrunnerWMC** [comment] 2019-07-24 06:02
Thanks for opening an issue with plenty of detail that I can easily follow! :)

Regarding the crash upon opening a blank tileset, this seems to be crashing at a call to [QImage.convertToFormat()](https://doc.qt.io/qt-5/qimage.html#convertToFormat). I don't see anything that should prevent this call from working on PySide; furthermore, it seems to always crash upon the _second_ call to that function, regardless of whether I call it on the QImage with alpha or the one without it first. That behavior is a bit nonsensical and points to it being a library bug.

In general, from my own past observations, PySide 2 currently has extremely buggy bindings for QImage and QPixmap (used by both Reggie and Puzzle for handling image data). I've encountered a lot of memory corruption issues that shouldn't happen, and don't happen at all on PyQt5. These include program crashes and image data getting corrupted in random ways. I've thought about filing a bug or bugs, but there are so many blatant problems with these two classes that seem to be reproducible across different computers and even operating systems that I figured they probably already know about it. Considering it's been like a year and nothing's changed, though... perhaps not.

The main reason I have PySide 2 support in this repo at all is for future-proofing, since it seems likely to me that PySide 2 will eventually replace PyQt5 someday. I think that by the time that happens, library bugs like this will probably have been fixed long ago. As such, for now I recommend sticking with PyQt5 until the Qt Company works out the bugs in PySide 2. Would that work for you, or do you have a reason you want to use PySide 2 currently? I could probably come up with some weird workaround if need be, but it seems a bit pointless when PyQt5 works fine now.

I will look at the other issues you mentioned -- which sound more like actual Puzzle bugs -- but don't have time right now. I'll get back to you in a day or two.

<sub>By the way, I like the perfect rectangular shape of that error message :)</sub>

**Comment by RoadrunnerWMC** [comment] 2019-07-24 06:08
One thing I should probably do, at least, is add a note to both respositories' readmes mentioning that PyQt5 is recommended over PySide 2 for stability reasons for the time being.
*(EDIT: done.)*

**Comment by YoYoBoBo** [comment] 2019-07-26 15:19
PyQt5 is perfectly fine for me :)

**Comment by YoYoBoBo** [comment] 2019-08-02 22:49
Random thing: It seems that Pass-Down is actually 0x40 and not 0x20. I tested it and 0x40 does give a pass-down effect albeit a little buggy. It kind of pushes mario through it, and mario cannot jump in the tile if the tile is placed above a block. 0x20 does nothing for me.

**Comment by RoadrunnerWMC** [comment] 2019-08-13 23:00
I know there are a few mistakes like that, although I don't remember exactly what they are. Thank you for pointing that one out.

Sorry it's taking me so long to get around to debugging this. I started looking into the saving issue, and it seems that something regarding U8 archive saving has broken in the wii.py modules. I'll research more later.

**Comment by RoadrunnerWMC** [comment] 2019-08-15 19:01
I just finished fixing that bug ^, and have also now changed it to use PyQt5 instead of PySide2 by default when both are available. I'll look into the incorrect collision things later. (I recall that another such mistake had to do with 1x2 slopes.)

@YoYoBoBo Could you please check that the tilesets you were having trouble saving now work correctly?

**Comment by YoYoBoBo** [comment] 2019-08-15 23:39
All of the tilesets now save and open correctly!

**Comment by RoadrunnerWMC** [comment] 2019-08-16 03:34
Great! I've changed pass-down to 0x40 as you suggested, as well.

I think that covers everything. Are there any remaining issues you're aware of (other than the PySide thing)?

**Comment by YoYoBoBo** [comment] 2019-08-16 04:08
I have not found any other issues with the program, everything seems to work well. I did find that the damage tile doesn’t seem to do damage and instead prevents you from wall jumping.

**Comment by RoadrunnerWMC** [comment] 2019-08-16 05:19
Huh, that's interesting. There definitely is a damage property; it's used in Newer Wii, among other places...

**Comment by YoYoBoBo** [comment] 2019-08-16 11:21
Yeah the spike property acts as a damage tile, that’s probably what was used. There is also another setting called “damage tile” in the last drop down list that doesn’t seem to do that.

**Comment by Zement** [comment] 2019-08-18 19:56
Yeah that's correct, the spike tile was used by Nintendo for the damage effect. The "damage tile" does indeed prevent wall-jumps. And I can also confirm 0x40 for the pass-down effect.

**Comment by RoadrunnerWMC** [comment] 2019-09-28 07:54
Sorry this is a... bit late, but I've changed "damage tile" to "anti wall jumps." If there's nothing else to fix at the moment, I'll close the issue.

**Closed as completed** 2020-09-14 00:13 UTC
